FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_EVOLUTION_API_URL
ARG VITE_USE_SOLAR_RESOURCE_API=true
ARG VITE_USE_UNIFIED_GENERATION=true
ARG VITE_USE_OM_COST_MODEL=true
ARG VITE_USE_DEGRADATION_ALL_CLIENTS=true
ARG VITE_USE_TUSD_TE_SIMPLIFIED=true
ARG VITE_USE_FINANCIAL_SHADOW_MODE=true
ARG VITE_USE_CHART_FIXED_SEASONAL_PROFILE=false
ARG VITE_GOOGLE_GEOCODING_API_KEY

ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
ENV VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
ENV VITE_EVOLUTION_API_URL=${VITE_EVOLUTION_API_URL}
ENV VITE_USE_SOLAR_RESOURCE_API=${VITE_USE_SOLAR_RESOURCE_API}
ENV VITE_USE_UNIFIED_GENERATION=${VITE_USE_UNIFIED_GENERATION}
ENV VITE_USE_OM_COST_MODEL=${VITE_USE_OM_COST_MODEL}
ENV VITE_USE_DEGRADATION_ALL_CLIENTS=${VITE_USE_DEGRADATION_ALL_CLIENTS}
ENV VITE_USE_TUSD_TE_SIMPLIFIED=${VITE_USE_TUSD_TE_SIMPLIFIED}
ENV VITE_USE_FINANCIAL_SHADOW_MODE=${VITE_USE_FINANCIAL_SHADOW_MODE}
ENV VITE_USE_CHART_FIXED_SEASONAL_PROFILE=${VITE_USE_CHART_FIXED_SEASONAL_PROFILE}
ENV VITE_GOOGLE_GEOCODING_API_KEY=${VITE_GOOGLE_GEOCODING_API_KEY}

RUN npm run build

FROM caddy:2.8-alpine AS runtime

WORKDIR /srv

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist /srv

EXPOSE 80 443

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget --spider --quiet http://localhost:80 || exit 1
