export const DEFAULT_TARIFF_KWH = 0.76;
export const DEFAULT_ANALYSIS_YEARS = 25;
export const DEFAULT_ANNUAL_INCREASE_PCT = 8;
export const DEFAULT_MODULE_DEGRADATION_PCT = 0.8;

export const DEFAULT_RENTABILITY_RATE_PER_KWH = DEFAULT_TARIFF_KWH;
export const DEFAULT_TARIFF_FALLBACK = DEFAULT_TARIFF_KWH;
