CREATE TABLE IF NOT EXISTS public.whatsapp_webhook_events (
    id bigint generated by default as identity primary key,
    received_at timestamp with time zone default now(),
    instance_name text,
    event text,
    headers jsonb,
    payload jsonb,
    error_log text
);

ALTER TABLE public.whatsapp_webhook_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon insert" ON public.whatsapp_webhook_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon select" ON public.whatsapp_webhook_events FOR SELECT USING (true);
