begin;

create table if not exists public.stripe_customers (
  org_id uuid primary key references public.organizations(id) on delete cascade,
  stripe_customer_id text not null unique,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.org_billing_timeline (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  event_type text not null,
  actor text not null default 'system',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_org_billing_timeline_org_created
  on public.org_billing_timeline(org_id, created_at desc);

create table if not exists public.billing_alerts (
  id bigint generated by default as identity primary key,
  org_id uuid references public.organizations(id) on delete cascade,
  severity text not null,
  code text not null,
  title text not null,
  detail text,
  payload jsonb not null default '{}'::jsonb,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_billing_alerts_open
  on public.billing_alerts(resolved_at, created_at desc)
  where resolved_at is null;

alter table public.organizations
  add column if not exists stripe_checkout_session_id text,
  add column if not exists stripe_price_id text,
  add column if not exists trial_days integer not null default 7;

create or replace function public.sync_org_access_state()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_count integer := 0;
  v_rows integer := 0;
begin
  update public.organizations
  set subscription_status = 'canceled',
      updated_at = v_now
  where subscription_status = 'trialing'
    and trial_ends_at is not null
    and trial_ends_at <= v_now;

  get diagnostics v_rows = row_count;
  v_count := v_count + v_rows;

  update public.organizations
  set subscription_status = 'unpaid',
      updated_at = v_now
  where subscription_status = 'past_due'
    and grace_ends_at is not null
    and grace_ends_at <= v_now;

  get diagnostics v_rows = row_count;
  v_count := v_count + v_rows;

  return v_count;
end;
$$;

create or replace function public.migrate_legacy_org_to_trial(
  p_org_id uuid,
  p_days integer default 7
)
returns table (
  org_id uuid,
  previous_status text,
  new_status text,
  trial_ends_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prev text;
  v_days integer := greatest(1, least(coalesce(p_days, 7), 30));
begin
  select o.subscription_status into v_prev
  from public.organizations o
  where o.id = p_org_id
  for update;

  if v_prev is null then
    raise exception 'organization_not_found';
  end if;

  update public.organizations
  set subscription_status = 'trialing',
      trial_started_at = coalesce(trial_started_at, now()),
      trial_ends_at = now() + make_interval(days => v_days),
      grace_ends_at = null,
      onboarding_state = coalesce(onboarding_state, '{}'::jsonb),
      updated_at = now()
  where id = p_org_id;

  insert into public.org_billing_timeline(org_id, event_type, actor, payload)
  values (
    p_org_id,
    'legacy_migrated_to_trial',
    'org_admin',
    jsonb_build_object('previous_status', v_prev, 'days', v_days)
  );

  return query
  select o.id, v_prev, o.subscription_status, o.trial_ends_at
  from public.organizations o
  where o.id = p_org_id;
end;
$$;

grant execute on function public.sync_org_access_state() to service_role;
grant execute on function public.migrate_legacy_org_to_trial(uuid, integer) to service_role;

commit;
