-- Create table for global AI settings
CREATE TABLE IF NOT EXISTS public.ai_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_active BOOLEAN DEFAULT false,
    personality_tone TEXT DEFAULT 'profissional e empático',
    openai_api_key TEXT, -- Optional: if users want to bring their own key, though env key is preferred
    daily_report_enabled BOOLEAN DEFAULT false,
    weekly_report_enabled BOOLEAN DEFAULT false,
    monthly_report_enabled BOOLEAN DEFAULT false,
    report_phone_number TEXT, -- Number to send reports to
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Initialize default settings row if it doesn't exist
INSERT INTO public.ai_settings (id, is_active)
SELECT 1, false
WHERE NOT EXISTS (SELECT 1 FROM public.ai_settings WHERE id = 1);

-- Create table for per-stage agent configuration
CREATE TABLE IF NOT EXISTS public.ai_stage_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_stage TEXT NOT NULL UNIQUE, -- e.g., 'novo_lead', 'respondeu', etc.
    is_active BOOLEAN DEFAULT false,
    agent_goal TEXT NOT NULL, -- The specific goal for this stage (e.g., "Fazer o lead responder")
    agent_prompt_template TEXT, -- Custom instructions for this stage
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed default stages and goals (based on user description)
INSERT INTO public.ai_stage_config (pipeline_stage, agent_goal, is_active) VALUES
('novo_lead', 'Fazer o Lead responder para mover para Respondeu', true),
('respondeu', 'Agendar Chamada para mover para Chamada Agendada', true),
('chamada_agendada', 'Garantir comparecimento e preparo para mover para Chamada Realizada', true),
('nao_compareceu', 'Entender motivos e reagendar para mover de volta para Chamada Agendada', true),
('chamada_realizada', 'Mover para Aguardando Proposta', false),
('aguardando_proposta', 'Gerar e apresentar proposta', false),
('proposta_pronta', 'Agendar apresentação da proposta', false),
('visita_agendada', 'Confirmar visita técnica', false),
('visita_realizada', 'Coletar feedback da visita', false),
('proposta_negociacao', 'Negociar valores e fechar contrato', false),
('financiamento', 'Auxiliar no processo de financiamento', false),
('contrato_assinado', 'Iniciar processo de instalação', false),
('projeto_pago', 'Confirmar recebimento', false),
('aguardando_instalacao', 'Agendar instalação', false),
('projeto_instalado', 'Confirmar instalação concluída', false),
('coletar_avaliacao', 'Pedir avaliação e indicações', false),
('contato_futuro', 'Manter relacionamento para futuro', false),
('perdido', 'Tentar reengajamento ou entender motivo da perda', false)
ON CONFLICT (pipeline_stage) DO UPDATE 
SET agent_goal = EXCLUDED.agent_goal;

-- Create table for AI Action Logs (Auditing)
CREATE TABLE IF NOT EXISTS public.ai_action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT REFERENCES public.leads(id) ON DELETE SET NULL,
    action_type TEXT NOT NULL, -- 'pipeline_move', 'message_sent', 'report_generated'
    stage_from TEXT,
    stage_to TEXT,
    details TEXT, -- JSON or text summary of what the AI did
    success BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security)
ALTER TABLE public.ai_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_stage_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_action_logs ENABLE ROW LEVEL SECURITY;

-- Create policies (open for now since auth is permissive in this dev environment, but good practice)
CREATE POLICY "Allow full access to ai_settings" ON public.ai_settings FOR ALL USING (true);
CREATE POLICY "Allow full access to ai_stage_config" ON public.ai_stage_config FOR ALL USING (true);
CREATE POLICY "Allow full access to ai_action_logs" ON public.ai_action_logs FOR ALL USING (true);

-- Enable Realtime for these tables so the UI updates instantly
alter publication supabase_realtime add table ai_settings;
alter publication supabase_stage_config add table ai_stage_config;
-- Note: 'supabase_stage_config' might not exist, usually it's just 'supabase_realtime'
alter publication supabase_realtime add table ai_stage_config;
alter publication supabase_realtime add table ai_action_logs;
