GRANT USAGE ON SCHEMA internal_crm TO authenticated;
GRANT USAGE ON SCHEMA internal_crm TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA internal_crm TO authenticated;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA internal_crm TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA internal_crm TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA internal_crm TO service_role;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA internal_crm TO authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA internal_crm TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA internal_crm
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA internal_crm
  GRANT ALL PRIVILEGES ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA internal_crm
  GRANT USAGE, SELECT ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA internal_crm
  GRANT USAGE, SELECT ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA internal_crm
  GRANT EXECUTE ON FUNCTIONS TO authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA internal_crm
  GRANT EXECUTE ON FUNCTIONS TO service_role;
